base: &base
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: twosnakes
  password: twosnakes

development:
  database: twosnakes_development
  <<: *base

test:
  database: twosnakes_test
  <<: *base
