source 'https://rubygems.org'

ruby '2.0.0'

gem 'active_model_serializers', '~> 0.7.0'
gem 'attribute_normalizer', '~> 1.1.0'
gem 'bootstrap-sass', '~> 2.3.1.0'
gem 'bcrypt-ruby', '~> 3.0.0'
gem 'jquery-rails', '~> 2.2.1'
gem 'jsend-rails', '~> 1.1.0'
gem 'pg', '~> 0.14.1'
gem 'rack-cors', '~> 0.2.7'
gem 'rails', '~> 4.0.0.beta1'
#gem 'sorcery', '~> 0.8.1'
gem 'sorcery', git: 'git://github.com/NoamB/sorcery.git' # https://github.com/NoamB/sorcery/issues/400
gem 'thin', '~> 1.5.0'
gem 'turbolinks', '~> 1.1.1'

group :development do
  gem 'awesome_print', '~> 1.1.0'
  gem 'foreman', '~> 0.61.0'
end

group :assets do
  gem 'sass-rails', '~> 4.0.0.beta1'
  gem 'coffee-rails', '~> 4.0.0.beta1'
  gem 'uglifier', '~> 1.0.3'
end
