source 'https://rubygems.org'

ruby '2.0.0'

gem 'active_model_serializers', '~> 0.7.0'
gem 'attribute_normalizer', '~> 1.1.0'
gem 'bcrypt-ruby', '~> 3.0.0'
gem 'jsend-rails', '~> 1.1.0'
gem 'pg', '~> 0.14.1'
gem 'rack-cors', '~> 0.2.7'
gem 'rails', '~> 3.2.12'
gem 'rails-api', '~> 0.0.3'
gem 'sorcery', '~> 0.8.1'
gem 'strong_parameters', '~> 0.2.0'
gem 'thin', '~> 1.5.0'

group :development do
  gem 'awesome_print', '~> 1.1.0'
  gem 'foreman', '~> 0.61.0'
end

group :development, :test do
  gem 'database_cleaner', '~> 0.9.1'
  gem 'dotenv', '~> 0.5.0'
  gem 'fabrication', '~> 2.6.2'
  gem 'faker', '~> 1.1.2'
  gem 'rspec-rails', '~> 2.13.0'
end
